# Site settings
title: Shamshad's Blog!
email: shamshad.npti@gmail.com
description: "Irresistible Math! :)"
baseurl: ""
url: ""
twitter_username: shamshad_saraindia
github_username:  shamshad.npti
comments: true
# Build settings
markdown: kramdown
permalink: pretty
