# Site settings
title: Hello!
email: shamshad.npti@gmail.com
description: "This site is maintained by me. The content, if not attributed, is my own opinion 
		or something that I have learned from experience over time. You may inform me if you find
		any part of the content inappropriate or misattributed"
baseurl: ""
url: ""
twitter_username: saralindia_shamshad
github_username:  shamshad.npti

# Build settings
markdown: kramdown
permalink: pretty
